[package]
name = "tundra"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enterpolation = { version = "0.2.1", features = ["linear"] }
palette = "0.7.6"
svg = "0.17.0"
