title = "Tundra color palette"

[base]
base-0 = "#081723"
base-1 = "#1f2e3c"
base-2 = "#374758"
base-3 = "#506275"
base-4 = "#6a7e93"
base-5 = "#929aa3"
base-6 = "#b9b7b2"
base-7 = "#e1d5c2"
base-8 = "#f0eae1"

[accents]
red = "#c45348"
vermilion = "#d37249"
orange = "#de904d"
yellow = "#e5b059"
olive = "#aea84a"
moss-green = "#799c4b"
green = "#428e54"
teal = "#008e84"
azure = "#0088ab"
blue = "#3e7bb6"
violet = "#8a68ae"
purple = "#bb5384"
light-red = "#fb8374"
light-vermilion = "#ff9d72"
light-orange = "#ffb974"
light-yellow = "#ffd57c"
light-olive = "#d9d070"
light-moss-green = "#a4c873"
light-green = "#70bd7f"
light-teal = "#11beb3"
light-azure = "#00b7dc"
light-blue = "#73a9e8"
light-violet = "#bb97e0"
light-purple = "#f083b4"
dark-red = "#862d27"
dark-vermilion = "#924626"
dark-orange = "#9a5e28"
dark-yellow = "#9f7630"
dark-olive = "#757125"
dark-moss-green = "#4b6827"
dark-green = "#1d5d2f"
dark-teal = "#005d56"
dark-azure = "#005874"
dark-blue = "#134e7d"
dark-violet = "#594077"
dark-purple = "#802d56"
