title = "Tundra color palette"

[base]
base-0 = "#081723"
base-1 = "#1f2e3c"
base-2 = "#374758"
base-3 = "#506275"
base-4 = "#6a7e93"
base-5 = "#929aa3"
base-6 = "#b9b7b2"
base-7 = "#e1d5c2"
base-8 = "#f0eae1"

[accents]
red = "#c15642"
vermilion = "#d67645"
orange = "#e6974c"
amber = "#f2b958"
yellow = "#f9db6b"
chartreuse = "#9ab758"
green = "#468d51"
teal = "#008c99"
blue = "#3e7bb6"
violet = "#7b6db3"
purple = "#a95c9a"
magenta = "#c25071"
light-red = "#f9856d"
light-vermilion = "#ffa16e"
light-orange = "#ffbe71"
light-amber = "#ffdc7a"
light-yellow = "#fffb89"
light-chartreuse = "#c2df7d"
light-green = "#74bd7d"
light-teal = "#00bcc9"
light-blue = "#73a9e8"
light-violet = "#ab9ce5"
light-purple = "#dc8bcb"
light-magenta = "#f8809f"
dark-red = "#842f21"
dark-vermilion = "#944923"
dark-orange = "#a06326"
dark-amber = "#a97d2f"
dark-yellow = "#ae983d"
dark-chartreuse = "#657c30"
dark-green = "#215c2d"
dark-teal = "#005b66"
dark-blue = "#134e7d"
dark-violet = "#4d447a"
dark-purple = "#723567"
dark-magenta = "#852a46"
