title = "Tundra color palette"

[base]
base-0 = "#060e1b"
base-1 = "#121d2d"
base-2 = "#293950"
base-3 = "#425876"
base-4 = "#5d799e"
base-5 = "#8594aa"
base-6 = "#abafb5"
base-7 = "#d0ccc0"
base-8 = "#f0eae1"

[accents]
red = "#e72056"
vermilion = "#fa5044"
orange = "#ff7932"
amber = "#ffa122"
yellow = "#fdc722"
chartreuse = "#9da91f"
green = "#4d842d"
teal = "#008eb4"
blue = "#4b66f6"
violet = "#a54bd7"
purple = "#d02aad"
magenta = "#e50c81"
light-red = "#ff6082"
light-vermilion = "#ff806c"
light-orange = "#ffa259"
light-amber = "#ffc64b"
light-yellow = "#ffe94b"
light-chartreuse = "#c8d34c"
light-green = "#7db45a"
light-teal = "#00c0e7"
light-blue = "#8994ff"
light-violet = "#d97cff"
light-purple = "#ff66e0"
light-magenta = "#ff5ab0"
dark-red = "#a10032"
dark-vermilion = "#af2523"
dark-orange = "#b74a0f"
dark-amber = "#b76a00"
dark-yellow = "#b18800"
dark-chartreuse = "#667200"
dark-green = "#28550e"
dark-teal = "#005d7c"
dark-blue = "#163eb0"
dark-violet = "#6e2597"
dark-purple = "#900076"
dark-magenta = "#a00053"
